eticaret/eticaret/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from main import views
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",views.index,name="index"),
    path("main/", include("main.urls")),
    path("to_do/", include("to_do.urls")),
    path('accounts/', include('accounts.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eticaret/main/urls.py
from django.urls import path,include
from .views import index,dynamic_view,formView,get_data
from . import views

app_name = 'main'
urlpatterns = [
    path("", index, name="index"),
    path("dynamic",dynamic_view,name="dynamic"),
    path("form",formView,name="form"),
    path("get_data/",get_data,name="get_data"),
    #path("users/",views.users,name="users"),
    #path("users/user/<int:id>/",views.user,name="user"),
    path('users/', views.UserListView.as_view(), name='users'),
    path('users/user/<int:pk>/', views.UserDetailView.as_view(), name='user'),
    path('users/user/new/', views.UserCreateView.as_view(), name='user_new'),
    path('users/user/<int:pk>/update/', views.UserUpdateView.as_view(), name='user_update'),
    path('users/user/<int:pk>/delete/', views.UserDeleteView.as_view(), name='user_delete'),
]   

eticaret/to_do/urls.py
from django.urls import path
from . import views


app_name = 'to_do'
urlpatterns = [
    # path('', views.index, name='index'),
    path('myview/', views.MyView.as_view(), name='myview'),
    path("templateview/",views.MyTemplateView.as_view(),name="templateview"),
    path("redirectview/",views.MyRedirectView.as_view(),name="redirectview"),
    path("myformview/",views.MyFormView.as_view(),name="myformview"),
    
    #real to do app
    path("", views.TodoListView.as_view(),name="todolistview"),
    path("add/",views.TodoCreateView.as_view(),name="todocreateview"),
    path("<int:pk>/update",views.TodoUpdateView.as_view(),name="todoupdateview"),
    path("<int:pk>/delete",views.TodoDeleteView.as_view(),name="tododeleteview"),
      
    #advanced
    path("advanced/",views.Advanced.as_view(),name="advancedlist"),
    
]

eticaret/to_do/models.py
from django.db import models

# Create your models here.

class ToDoItem(models.Model):
    title=models.CharField(max_length=100)
    complated=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title

eticaret/to_do/forms.py
from django import forms

from .models import ToDoItem

class ToDoItemForm(forms.ModelForm):
    class Meta:
        model=ToDoItem
        fields=['title','complated']


eticaret/to_do/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.http import HttpResponse
from .models import ToDoItem
from .forms import ToDoItemForm
from django.urls import reverse_lazy
from django.views.generic import (
    View,
    TemplateView,
    RedirectView,
    FormView,
    ListView,

    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    
)


# def index(request):
#     return render(request, "to_do/index.html")

class MyView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "to_do/index.html",{})

    def post(self, request, *args, **kwargs):
        return HttpResponse("Hello, this is a POST request!")
    
class MyTemplateView(TemplateView):
    template_name="to_do/index.html"
    
class MyRedirectView(RedirectView):
    url="/to_do"
    
class MyFormView(FormView):
    template_name="to_do/index.html"
    form_class=ToDoItemForm
    success_url=reverse_lazy("to_do:myformview")
    
    def form_valid(self, form):
        
        #form lcass "from" adlı değişkende gönderilir template'e
        #form gecerli ise burada formla islemler yapilir
        # Form doğrulandıysa yapılacak islemler
        form.save()
        # print(form.cleaned_data)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
            # Şablona ekstra veri eklemek için
            #sablona eklenen veriler context adıyla gecer
            context = super().get_context_data(**kwargs)
            context["page_title"] = "Contact Us"  # Başlık ekliyoruz
            return context
        
class TodoListView(ListView):
    model=ToDoItem
    template_name="to_do/index.html"
    success_url= "to_do:index"
    context_object_name="todoitems"
    ordering=["-created"]

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context["page_title"]="To Do App"
        
        return context

class TodoCreateView(CreateView):
    template_name="to_do/index.html"
    model=ToDoItem
    fields=["title","complated"]
    success_url="/to_do"
    
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context["page_title"]="Add new"
        
        return context
    
class TodoUpdateView(UpdateView):
    template_name="to_do/index.html"
    model=ToDoItem
    fields=["title","complated"]
    success_url="/to_do"
    
class TodoDeleteView(DeleteView):
    template_name="to_do/index.html"
    model=ToDoItem
    success_url="/to_do"

class Advanced(ListView):
    model = ToDoItem
    template_name = 'to_do/advanced.html'
    context_object_name = 'todoitems'
    ordering = ['-created']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_form'] = ToDoItemForm()
        # Her öğe için bir düzenleme formu oluştur
        context['edit_forms'] = {item.id: ToDoItemForm(instance=item) for item in context['todoitems']}
        return context

    def post(self, request, *args, **kwargs):
        if 'create_form' in request.POST:
            create_form = ToDoItemForm(request.POST)
            if create_form.is_valid():
                create_form.save()
                return redirect('to_do:advancedlist')
        elif 'edit_form' in request.POST:
            item_id = request.POST.get('item_id')
            item = ToDoItem.objects.get(id=item_id)
            edit_form = ToDoItemForm(request.POST, instance=item)
            if edit_form.is_valid():
                edit_form.save()
                return redirect('to_do:advancedlist')
        elif 'delete_form' in request.POST:
            item_id = request.POST.get('item_id')
            item = ToDoItem.objects.get(id=item_id)
            item.delete()
            return redirect('to_do:advancedlist')
        return self.get(request, *args, **kwargs)

eticaret/to_do/templates/to_do/advanced.html
{% extends "main/base.html" %}
{% block content %}
<style>
    .item-box {
        border: 2px solid greenyellow;
        border-radius: 10px;
        margin-top: 20px;
        width: 400px;
    }
</style>

{% if todoitems %}
    {% for todoitem in todoitems %}
        <div class="item-box">
            <h1>{{ todoitem.title }}</h1>
            <h2>{{ todoitem.completed }}</h2>
            <form method="post" >
                {% csrf_token %}
                <input type="hidden" name="item_id" value="{{ todoitem.id }}">
                <button type="submit" name="delete_form">Delete</button>
            </form>
             <form method="post">
                {% csrf_token %}
                <input type="hidden" name="item_id" value="{{ todoitem.id }}">
                {{ edit_forms.todoitem.id.as_p }}
                <button type="submit" name="edit_form">Edit</button>
            </form>
        </div>
    {% endfor %}
{% else %}
    <h1>No item found</h1>
{% endif %}

{% if create_form %}
<h4 style="margin-top: 10px;">add new item</h4>
    <form method="post" style="margin-top: 10px;">
        {% csrf_token %}
        {{ create_form.as_p }}
        <button type="submit" style="width: 100%;" name="create_form">Submit</button>
    </form>
{% endif %}
{% endblock %}

eticaret/to_do/templates/to_do/index.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}

  {% if page_title %}
    {{ page_title }}
  {% endif %}
{% endblock %}

{% block content %}
<h1> {{zort}} </h1>
<header>
    <ul>
        <li>
            <a href="{% url 'to_do:advancedlist' %}"> to_do advanced</a>
        </li>
    </ul>
</header>
<style>
    .item-box{
        padding: 20px;
        background-color: bisque;
        border: 2px solid greenyellow;
        border-radius: 10px;
        margin-top: 20px;
        width: 400px;
    }
</style>
<a href="{% url "to_do:todocreateview"%}">Add new item</a>
{% if todoitems%}
{% for todoitem in todoitems %}
    <div class="item-box">
        <h1>{{todoitem.title}}</h1>
        <h2>{{todoitem.complated}}</h2>
        <a href="{% url "to_do:todoupdateview" todoitem.pk%}">edit</a>
        <a href="{% url "to_do:tododeleteview" todoitem.pk%}">delete</a>
    </div>
{%endfor%}
{%else%}
<h1>no item found</h1>
{%endif%}

  {% if form %}
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      
      <button type="submit">Submit</button>
    </form>
  {% endif %}

  
  {% comment %} {% include 'main/dynamic.html' %} {% endcomment %}
{% endblock %}