eticaret/accounts/urls.py
# accounts/urls.py
from django.urls import path
from .views import user_login,home,user_logout,user_register

app_name="accounts"
urlpatterns = [
    path('', home, name='home'),
    path('register/', user_register, name='register'),
    path('login/', user_login , name='login'),
    path('logout/', user_logout, name='logout'),
]



eticaret/eticaret/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from main import views
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",views.index,name="index"),
    path("main/", include("main.urls")),
    path("to_do/", include("to_do.urls")),
    path('accounts/', include('accounts.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eticaret/main/urls.py
from django.urls import path,include
from .views import index,dynamic_view,formView,get_data
from . import views

app_name = 'main'
urlpatterns = [
    path("", index, name="index"),
    path("dynamic",dynamic_view,name="dynamic"),
    path("form",formView,name="form"),
    path("get_data/",get_data,name="get_data"),
    #path("users/",views.users,name="users"),
    #path("users/user/<int:id>/",views.user,name="user"),
    path('users/', views.UserListView.as_view(), name='users'),
    path('users/user/<int:pk>/', views.UserDetailView.as_view(), name='user'),
    path('users/user/new/', views.UserCreateView.as_view(), name='user_new'),
    path('users/user/<int:pk>/update/', views.UserUpdateView.as_view(), name='user_update'),
    path('users/user/<int:pk>/delete/', views.UserDeleteView.as_view(), name='user_delete'),
]   

eticaret/to_do/urls.py
from django.urls import path
from . import views


app_name = 'to_do'
urlpatterns = [
    # path('', views.index, name='index'),
    path('myview/', views.MyView.as_view(), name='myview'),
    path("templateview/",views.MyTemplateView.as_view(),name="templateview"),
    path("redirectview/",views.MyRedirectView.as_view(),name="redirectview"),
    path("myformview/",views.MyFormView.as_view(),name="myformview"),
    
    #real to do app
    path("", views.TodoListView.as_view(),name="todolistview"),
    path("add/",views.TodoCreateView.as_view(),name="todocreateview"),
    path("<int:pk>/update",views.TodoUpdateView.as_view(),name="todoupdateview"),
    path("<int:pk>/delete",views.TodoDeleteView.as_view(),name="tododeleteview"),
      
    #advanced
    path("advanced/",views.Advanced.as_view(),name="advancedlist"),
    
]

eticaret/main/models.py
from django.db import models
from django.urls import reverse

# Create your models here.



#This! is the proper model    
class User(models.Model):
    name=models.CharField(max_length=100)
    email=models.EmailField()
    points=models.IntegerField()
    is_active=models.BooleanField(default=True)

    #dinamik url olusturup kolayca cagirmak icin    
    def get_absolute_url(self):
        return reverse("main:user",kwargs={"pk":self.id})

eticaret/main/forms.py
from django import forms
from .models import User

#This! is the proper form from a model
class UserForm(forms.ModelForm):
    name=forms.CharField(max_length=100,required=False,widget=forms.TextInput(attrs={'placeholder': 'your name sir'}))
    is_active=forms.BooleanField(required=False)
    class Meta:
        model = User
        fields = ['name', 'email', 'points']

eticaret/main/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic import DetailView
from .models import User
from .forms import UserForm
from . import forms
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from django.urls import reverse

def index(request):
    if User.objects.count() > 0:
        pros={
            "users":User.objects.all()
        }
    else:
        pros={}
    return render(request, "main/index.html",pros)

def dynamic_view(request):
    

    if request.method == "POST":
        name = request.POST.get('name')
        last_name = request.POST.get('last_name')
        pros={
            "name":name,
            "last_name":last_name
        }
       
        return render(request, "main/dynamic_content.html", pros)

    return render(request, "main/dynamic.html")


def get_data(request):
    data={"data": "very effective way of get data"}
    return render(request, "main/get_data.html", data)


#This! is the proper form view
def formView(request):
    form = UserForm(request.POST or None)
    form.fields['name'].widget.attrs.update({'placeholder': 'overrided placeholder'})
    if form.is_valid():
        # User.objects.create(**form.cleaned_data) gelen datadan obje olusturur
        form.save()
        form = UserForm()
    context = {
        "form": form
    }
    return render(request, "main/form.html", context)

"""
def users(request):
    users = User.objects.all()
    return render(request, "main/users.html", {"users": users})
    """ 
"""
def user(request,id):
    user = get_object_or_404(User, id=id)
    
    return render(request, "main/user.html", {"user": user})
"""

class UserListView(ListView):
    model = User
    template_name = "main/users.html"
    context_object_name = "users"
    
class UserDetailView(DetailView):
    model = User
    template_name = "main/user.html"
    context_object_name = "user"

class UserCreateView(CreateView):
    model = User
    form_class = forms.UserForm
    template_name = "main/form.html"
    success_url = "/users/"
    
class UserUpdateView(UpdateView):
    model = User
    form_class = forms.UserForm
    template_name = "main/form.html"
    success_url = "/users/"

class UserDeleteView(DeleteView):
    model = User
    template_name = "main/form.html"
    #success_url = "/users/"
    
    def get_success_url(self):
        return reverse("main:users")
    

eticaret/main/templates/main/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Site{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://unpkg.com/htmx.org@2.0.0/dist/htmx.min.js"></script>

    
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
</head>
<body>
    <header>
        <ul>
            <li>
                <a href="{% url 'main:index' %}"> index</a>
            </li>
            <li>
                <a href="{% url 'main:dynamic' %}"> dynamic</a>
            </li>
            <li>
                <a href="{% url 'main:form' %}"> form</a>
            </li>
            <li>
                <a href="{% url 'to_do:todolistview' %}"> to_do index</a>
            </li>
            <li>
                <a href="{% url 'accounts:home' %}"> accounts</a>
            </li>
        </ul>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        <p>&copy; 2023 My Site</p>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
    
    <script src="{%static 'scripts/app.js'%}"></script>
</body>
</html>

eticaret/main/templates/main/dynamic.html
{% extends 'main/base.html' %}

{% block title %}
  My Site Dynamic Page
{% endblock %}

{% block content %}
  <form method="post" hx-post="{% url 'main:dynamic' %}" hx-target="#dynamic-content" hx-swap="innerHTML">
    {% csrf_token %}
    <input type="text" name="name" id="name" />
    <input type="text" name="last_name" id="last_name" />
    <button type="submit">Submit</button>
  </form>

  <div id="dynamic-content" style="width: 100%;">
   
      {% comment %} {% include 'main/dynamic_content.html' %} {% endcomment %}
    
  </div>
{% endblock %}

eticaret/main/templates/main/dynamic_content.html
<div style="width: 100%; height: 500px;
background-color: black; display: flex; justify-content: center;
 align-items: center; color: white; font-size: 2rem;">

 {{name}}
        {{last_name}}
</div>
       

eticaret/main/templates/main/form.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}My Site Form Page{% endblock %}
{% block content %}

{% if form %}
{% load crispy_forms_tags %}
<form method="post" >
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary w-100">Submit</button>
</form>
{% endif %}
<hr style="height: 10px;width: 100%; margin-bottom: 30px; color:black;">

{%if personForm%}

<form method="post" >
    {% csrf_token %}
    {{ personForm|crispy }}
    <button type="submit" class="btn btn-primary w-100">Submit</button>

</form>
{% endif %}


{% endblock %}

eticaret/main/templates/main/get_data.html

{{data}}


eticaret/main/templates/main/index.html
{%extends "main/base.html" %}
{%load static%}
{%block title%}My Site Index Page{%endblock%}
{%block content%}
<main>
<h1>Welcome to the Index Page</h1>  
<p>This is the content of the index page.</p>
<div class="grid-box">
  {%if users%}
    {%for user in users%}
      <div class="grid-box-item">
        <h2>{{user.name}}</h2>
        <p>{{user.email}}</p>
        <a href="{% url 'main:users'%}"> user page </a>
      </div>
    {%endfor%}
  {%else%} 
  <div class="grid-box-item">No user found</div>
  <div class="grid-box-item">No user found</div>
  <div class="grid-box-item">No user found</div>
  <div class="grid-box-item">No user found</div>
  {%endif%}
</div>

 {# url 'main:get_data' böyle kullanımda appName  :   urlName sen hep süreklü / koyuyorsun araya o yanlış #}
 {# This is a comment in a Django template. It will not appear in the output HTML. #}


<div class="swiper-box">
    <div class="swiper mySwiper">
        <div class="swiper-wrapper">
          <div class="swiper-slide">Slide 1</div>
          <div class="swiper-slide">Slide 2</div>
          <div class="swiper-slide">Slide 3</div>
          <div class="swiper-slide">Slide 4</div>
          <div class="swiper-slide">Slide 5</div>
          <div class="swiper-slide">Slide 6</div>
          <div class="swiper-slide">Slide 7</div>
          <div class="swiper-slide">Slide 8</div>
          <div class="swiper-slide">Slide 9</div>
        </div>
      </div>
</div>

<button hx-get="{% url 'main:get_data' %} " 
hx-target="#result">Click me</button>
<div id="result"></div>


</main>
{%endblock%}

eticaret/main/templates/main/user.html
{%extends "main/base.html" %}
{%load static%}
{%block title%}My Site Index Page{%endblock%}
{%block content%}

<style>
    .user-card{
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        margin-top: 20px;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 10px;
        color: palegreen;
        font-size: 30px;
    }
</style>
{%if user%}
<div class="user-card">
    <p>{{user.name}}</p>
    
    <p>{{user.email}}</p>
</div>
    

{%endif%}

{%endblock%}



eticaret/main/templates/main/users.html
{%extends "main/base.html" %}
{%load static%}
{%block title%}My Site Index Page{%endblock%}
{%block content%}

<style>
  body{
    background-color: #5f8248;
  }
</style>
{%if users%}
  <div class="grid-box">
    {%for user in users%}
      <div class="grid-box-item">
        <h2>{{user.name}}</h2>
        <p>{{user.email}}</p>
        <!-- <a href="{% url 'main:user' user.id %}"> user page </a> -->
        <a href="{{ user.get_absolute_url }}"> user page </a> 
        <!-- bu da alternatif bir yontem fonksiyon icin models e bakınız 
            (in models.py)
            def get_absolute_url(self):
                return reverse("main:user",kwargs={"id":self.id}) 
        --->
      </div>
    {%endfor%}
  </div>
{%else%} 
  <div class="grid-box-item">No user found</div>
  <div class="grid-box-item">No user found</div>
  <div class="grid-box-item">No user found</div>
  <div class="grid-box-item">No user found</div>
{%endif%}




{%endblock%}